#!/usr/bin/env python3
"""genfontatlas.py — bake a proportional anti-aliased UI font into Zag source.

Rasterizes Fira Sans (system OTF, SIL OFL licensed) at the PrismStudio
typography roles and emits src/fontatlas.zag:

  face 0  body     Fira Sans Regular 13px   default UI text
  face 1  body-med Fira Sans Medium  13px   emphasis, active states
  face 2  dense    Fira Sans Regular 12px   outliner rows, timeline, status
  face 3  section  Fira Sans Medium  15px   panel titles, section headers
  face 4  title    Fira Sans Medium  18px   app title, large headings

Per-glyph 8-bit coverage is base64-embedded (Zag string literals carry no
\\xNN escapes) and decoded once at startup by fb.zag. Glyph metrics are packed
one i64 per glyph so text measurement needs no framebuffer.

Regenerate with:  python3 tools/genfontatlas.py
"""

import base64
import os
import sys

from PIL import Image, ImageDraw, ImageFont

REG = "/usr/share/fonts/opentype/fira/FiraSans-Regular.otf"
MED = "/usr/share/fonts/opentype/fira/FiraSans-Medium.otf"

FACES = [
    ("body 13 regular", REG, 13),
    ("body 13 medium", MED, 13),
    ("dense 12 regular", REG, 12),
    ("section 15 medium", MED, 15),
    ("title 18 medium", MED, 18),
]

# HiDPI: every face is additionally baked at each integral UI scale, so a 2x
# display rasterizes real 26px outlines instead of doubling 13px coverage.
# Face index is `logical_face + (scale - 1) * len(FACES)`; layout always uses
# the 1x metrics so the logical geometry is identical at every scale.
SCALES = [1, 2, 3]

FIRST, LAST = 32, 126  # inclusive printable ASCII
PAD = 8                # raster scratch padding


def render_glyph(font, ch, px):
    """Return (adv, bx, by, w, h, bytes) for one glyph.

    bx/by are the ink offset from the pen position at the line-box top-left:
    blit position = (pen_x + bx, line_top + by).

    The scratch canvas is sized from the em so large HiDPI faces (up to 54px)
    are never clipped by a fixed bound.
    """
    adv = font.getlength(ch)
    span = PAD * 2 + px * 3
    img = Image.new("L", (span, span), 0)
    d = ImageDraw.Draw(img)
    d.text((PAD, PAD), ch, font=font, fill=255)
    box = img.getbbox()
    if box is None:
        return adv, 0, 0, 0, 0, b""
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    data = img.crop(box).tobytes()
    return adv, x0 - PAD, y0 - PAD, w, h, data


def main():
    out = os.path.join(os.path.dirname(__file__), "..", "src", "fontatlas.zag")
    blob = bytearray()
    glyphs = {}   # (face, ch) -> packed i64
    metrics = []  # per face: (ascent, descent)

    # Faces are emitted scale-major: [1x faces..., 2x faces..., 3x faces...].
    all_faces = [(label, path, px * sc, sc)
                 for sc in SCALES for (label, path, px) in FACES]

    for fi, (label, path, px, sc) in enumerate(all_faces):
        font = ImageFont.truetype(path, px)
        ascent, descent = font.getmetrics()
        metrics.append((ascent, descent))
        for code in range(FIRST, LAST + 1):
            adv, bx, by, w, h, data = render_glyph(font, chr(code), px)
            advq = int(round(adv))
            off = len(blob)
            blob.extend(data)
            if not (0 <= advq < 128 and -32 <= bx < 96 and -16 <= by < 112
                    and 0 <= w < 128 and 0 <= h < 128 and off < (1 << 29)):
                sys.exit(f"metric overflow: face {fi} ({label} @{px}px) ch {code} "
                         f"adv={advq} bx={bx} by={by} w={w} h={h} off={off}")
            packed = (advq | ((bx + 32) << 7) | ((by + 16) << 14)
                      | (w << 21) | (h << 28) | (off << 35))
            glyphs[(fi, code)] = packed

    b64 = base64.b64encode(bytes(blob)).decode()
    chunks = [b64[i:i + 2000] for i in range(0, len(b64), 2000)]

    lines = []
    a = lines.append
    a("// fontatlas.zag — GENERATED by tools/genfontatlas.py. Do not hand-edit.")
    a("//")
    a("// Proportional anti-aliased UI font (Fira Sans, SIL OFL) baked as 8-bit")
    a("// coverage at multiple integral UI scales. Layout uses 1x metrics")
    a("// (faces 0..fa_face_count()-1) so logical geometry is scale-invariant;")
    a("// draw_glyph picks the baked face for the current scale and blits real")
    a("// physical-resolution coverage — no nearest-neighbor replication.")
    a("//")
    a(f"// Logical faces (1x): 0 body 13R, 1 body 13M, 2 dense 12R, 3 section 15M,")
    a(f"// 4 title 18M. Scales: {SCALES}. Baked face index =")
    a(f"//   logical_face + (scale - 1) * fa_face_count()")
    a("//")
    a("// Packed metric record (one i64 per glyph, 0 for unprintable):")
    a("//   bits 0..6   advance (7 bits, 0..127)")
    a("//   bits 7..13  bearing_x + 32 (7 bits, -32..95)")
    a("//   bits 14..20 bearing_y + 16 (7 bits, -16..111)")
    a("//   bits 21..27 width (7 bits, 0..127)")
    a("//   bits 28..34 height (7 bits, 0..127)")
    a("//   bits 35..   coverage offset (29 bits)")
    a("// Coverage lives in base64 chunks decoded once at startup (fb.zag).")
    a("")
    a(f"fn fa_face_count() i32 {{ return {len(FACES)}; }}")
    a(f"fn fa_scale_count() i32 {{ return {len(SCALES)}; }}")
    a(f"fn fa_cov_len() i32 {{ return {len(blob)}; }}")
    a("")
    asc = " ".join(f"if (face == {i}) {{ return {m[0]}; }}" for i, m in enumerate(metrics))
    dsc = " ".join(f"if (face == {i}) {{ return {m[1]}; }}" for i, m in enumerate(metrics))
    a("fn fa_ascent(face: i32) i32 { %s return %d; }" % (asc, metrics[0][0]))
    a("fn fa_descent(face: i32) i32 { %s return %d; }" % (dsc, metrics[0][1]))
    a("fn fa_line_h(face: i32) i32 { return fa_ascent(face) + fa_descent(face); }")
    a("")
    a("// Packed metric record for one glyph; 0 for anything unprintable.")
    a("// `face` is a BAKED face index (0..fa_face_count()*fa_scale_count()-1).")
    a("// Layout code should pass a logical face (0..fa_face_count()-1) which")
    a("// selects the 1x bake and yields logical-pixel metrics.")
    a("fn fa_g(face: i32, ch: i32) i64 {")
    a(f"    if (ch < {FIRST} || ch > {LAST}) {{ return 0; }}")
    n_baked = len(all_faces)
    for fi in range(n_baked):
        a(f"    if (face == {fi}) {{ return fa_g{fi}(ch); }}")
    a("    return fa_g0(ch);")
    a("}")
    a("")
    for fi in range(n_baked):
        a(f"fn fa_g{fi}(ch: i32) i64 {{")
        for code in range(FIRST, LAST + 1):
            a(f"    if (ch == {code}) {{ return {glyphs[(fi, code)]}; }}")
        a("    return 0;")
        a("}")
        a("")
    a("fn fa_adv(face: i32, ch: i32) i32 { return (fa_g(face, ch) & 127) as i32; }")
    a("fn fa_bx(face: i32, ch: i32) i32 { return (((fa_g(face, ch) >> 7) & 127) as i32) - 32; }")
    a("fn fa_by(face: i32, ch: i32) i32 { return (((fa_g(face, ch) >> 14) & 127) as i32) - 16; }")
    a("fn fa_w(face: i32, ch: i32) i32 { return ((fa_g(face, ch) >> 21) & 127) as i32; }")
    a("fn fa_h(face: i32, ch: i32) i32 { return ((fa_g(face, ch) >> 28) & 127) as i32; }")
    a("fn fa_off(face: i32, ch: i32) i32 { return (fa_g(face, ch) >> 35) as i32; }")
    a("")
    a(f"fn fa_chunk_count() i32 {{ return {len(chunks)}; }}")
    a("fn fa_chunk(i: i32) []u8 {")
    for i, c in enumerate(chunks):
        a(f'    if (i == {i}) {{ return "{c}"; }}')
    a('    return "";')
    a("}")
    a("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(blob)} coverage bytes, {len(chunks)} chunks, "
          f"{len(lines)} lines")


if __name__ == "__main__":
    main()
